{% set name = "sagemaker-mxnet-serving-container" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.zip
  sha256: 9dbc58597a2c7594656b82c4fc6a2baae492f44887a45e2af38dbf4b08ff7188

build:
  noarch: python
  number: 0
  entry_points:
    - serve=sagemaker_mxnet_serving_container.serving:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - retrying

test:
  imports:
    - sagemaker_mxnet_serving_container

about:
  home: https://github.com/aws/sagemaker-mxnet-containers
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Open source library for creating MXNet containers to run on Amazon SageMaker.
  dev_url: https://github.com/aws/sagemaker-mxnet-serving-container

extra:
  recipe-maintainers:
    - oblute
    - benhuff
    - rluria14
